services:
  lw_nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    container_name: lw_nginx
    restart: always
    ports:
      - "80:80"
  lw_fastapi:
    build:
      context: .
      dockerfile: ./containers/fastapi/Dockerfile
    container_name: lw_fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - lw_postgres
  lw_postgres:
    image: postgres:16
    container_name: lw_postgres
    restart: always
    environment:
      POSTGRES_USER: lwuser
      POSTGRES_PASSWORD: 7ubtZX1WuggN
      POSTGRES_DB: practice
      TZ: "Asia/Tokyo"
    ports:
      - "15450:5432"
